### ISSUE TITLE
Image checksum fails in some cases

### ISSUE THREAD

**Issue by EsdrasVP** [fogbow/sebal-scheduler#71]
Sometimes, Fetcher gets

> ERROR CheckSumMD5ForFile:50 - java.io.IOException: Some file in /local/exports/results/LT52150651993225CUB00 is corrupted or present some error

while comparing checksum from result files. We need to investigate why this is happening.

**Comment by thiagomanel** [comment]
two questions
- does this happen in every fetch trial?
- is it possible to double check this sum for this file (say, ssh into fetcher and crawler VMs to call sum)

**Comment by EsdrasVP** [comment]
This does not happen in every fetch trial, but happened with 14 images.

Curiously, this problem happened with images from 1992 to 1995 (not all of them though).

I have tested checksum using both Java Md5 Checksum API and md5sum (from linux system) for a file with 362MB and everything works fine. So this problem might be a particular case for this fetch try.

What we could do to verify this is mark these images as NOT_DOWNLOADED, so we can monitor job from start.

**Comment by EsdrasVP** [comment]
The problem was caused by multiple checksum files for the same corresponding output. 

For instance, in image LT52150651993225CUB00 folder:
- LT52150651993225CUB00_new_NDVI.nc.<old-file-checksum>.md5
- LT52150651993225CUB00_new_NDVI.nc.<new-file-checksum>.md5

So when Fetcher generated the checksum, it compared its value with the old file, which was different from the new one.

This was caused by consecutive Scheduler relaunchs, when an image was executed and had checksums generated for each file, but, suddenly, system was restarted, maintaining old files in image folder.
