### ISSUE TITLE
USGS does not allow a user to request 10 image download links without accessing it

### ISSUE THREAD

**Issue by EsdrasVP** [fogbow/sebal-scheduler#72]
We detected that USGS does not allow a user to have more than 10 download links without aceesing it.

Since bootstrap stores a list of images in database with NOT_DOWNLOADED state, take some time until Crawler access these links to download them all.

**Comment by thiagomanel** [comment]
I think we should:
- Get in touch with USGS to request an increase in this limit;
- handle this failure in the catalog. Note that, even though we receive an increase in download quota, we can still reach it. Maybe we should add a new state to model images that were just submitted but we were not able to get the download link yet (then we should retry to get them periodically).

@EsdrasVP , does it make sense to you?

**Comment by EsdrasVP** [comment]
@thiagomanel yes, it does. I'll get in touch with USGS to see the viability of increasing this limit.

**Comment by EsdrasVP** [comment]
An alternative for this is limit number of years per job addition.

**Comment by EsdrasVP** [comment]
Solved in above commit.
