### ISSUE TITLE
SebalMain only receives one Crawler as parameter

### ISSUE THREAD

**Issue by EsdrasVP** [fogbow/sebal-scheduler#79]
Scheduler component's main routine (SebalMain) receives Crawler address and port in its args when starting to execute. The problem with this is that Scheduler stays binded to a single Crawler. If, for instance, an Azure Worker is deployed, it will not receive the correct IP and port to mount Azure Crawler's /local/exports directory.

While executing, Scheduler need to get this data from other source in order to support more than one Crawler.

**Comment by thiagomanel** [comment]
or to receive from the same source. That is, receive as argument a list such as: addr1:port1;addr2:port2 and so on

**Comment by fubica** [comment]
On Nov 3, 2016, at 11:08 , Thiago Emmanuel Pereira notifications@github.com wrote:

> or to receive from the same source. Tthat is, receive as argument a list such as: addr1:port1;addr2:port2 and so on

Originally, I believe the design was different. The address and port should be fields in the db that were updated by the respective crawler. Before setting the state of the image as downloaded, the crawler should update the centralized db with the appropriate addr1:port, but I might be missing something here.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

---

 Francisco Vilar Brasileiro                                   VoIP:  +55 83 1075 2038
 Departamento de Sistemas e Computação   Fone:  +55 83 2101 1644
 Universidade Federal de Campina Grande   Fax:    +55 83 2101 1498
 58.429-900, Campina Grande, PB, Brasil      E-mail: fubica@dsc.ufcg.edu.br
